////
Copyright 2023 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#design]
= Design Decisions
:idprefix: design_

== C++14 Requirement

=== Constexpr Support

Using C++14's relaxed definition of `constexpr` nearly all functionality of the library can be constexpr.
This allows Boost.Decimal to better emulate the functionality a built-in type would have.

=== Boost.Math Integration

Boost.Math requires C++14 as the minimum language standard for the library.
By meeting this requirement, and Boost.Math's conceptual requirements for a user-defined type we are able to provide the statistics, interpolation, quadrature, etc. out of the box.

=== No Binary Floating Point Operations
The library deliberately does not contain any operations between a binary floating point type and the decimal floating point types.
The rationale is similar to that of the library in the first place in that you may end up with surprising results.
Conversion operators and constructors are available for all decimal types should the user want to explicit cast one side of the operation to conduct the operation.
