////
Copyright 2023 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#overview]
= Overview
:idprefix: overview_

== Description

Boost.Decimal is an implementation of IEEE 754 Decimal Floating Point numbers.
The library is header-only and requires C++14.

== Motivation

Current C++ floating point types store the significand (often incorrectly referred to as the mantissa) as binary digits.
Famously this leads to rounding errors: https://0.30000000000000004.com.
Decimal floating point numbers avoid this issue by storing the significand in base-10 (decimal).
The other major difference between binary and decimal floating point types is that the latter allows for multiple representations of the same number.
For example 1e5 could also be stored as 0.1e6, 0.01e7, so on and so forth.
These are referred to as cohorts which binary does not have as there is only one way to represent each number in binary floating point.

== Supported Compilers

* GCC 6 or later
* Clang 5 or later
* Visual Studio 2017 or later

Tested on https://github.com/cppalliance/decimal/actions[Github Actions] and https://drone.cpp.al/cppalliance/decimal[Drone].
Coverage can be found on https://app.codecov.io/gh/cppalliance/decimal[Codecov].
