site:
  title: Boost.Decimal
  start_page: decimal::index.adoc
content:
  sources:
    - url: ..
      start_path: doc
      branches: HEAD
output:
  dir: html
ui:
  bundle:
    url: https://github.com/boostorg/website-v2-docs/releases/download/ui-master/ui-bundle.zip
  output_dir: decimal/_
