////
Copyright 2023 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#cmath]
= cmath support
:idprefix: cmath_

== <cmath>

Decimal contains overloads for all functions from `<cmath>`, and they have the same handling as built-in floating point types.
They are also all constexpr with C\\++14 unlike the built-in floating point types which require either C++23 or 26.

=== Basic Operations

|===
| Function | Description
| https://en.cppreference.com/w/cpp/numeric/math/fabs[abs] | Absolute Value
| https://en.cppreference.com/w/cpp/numeric/math/fabs[fabs] | Floating Point Absolute Value (Identical to `abs`)
| https://en.cppreference.com/w/cpp/numeric/math/fmod[fmod] | Floating Point Modulo Operation
| https://en.cppreference.com/w/cpp/numeric/math/remainder[remainder] | Signed Floating Point Modulo
| https://en.cppreference.com/w/cpp/numeric/math/remquo[remquo] | Signed remainder and at least three bits of division result (quotient)
| https://en.cppreference.com/w/cpp/numeric/math/fma[fma] | Fused Multiply - Add
| https://en.cppreference.com/w/cpp/numeric/math/fmax[fmax] | Returns maximum value
| https://en.cppreference.com/w/cpp/numeric/math/fmin[fmin] | Returns minimum value
| https://en.cppreference.com/w/cpp/numeric/math/fdim[fdim] | Returns unsigned difference of two values
| https://en.cppreference.com/w/cpp/numeric/math/nan[nan] | Generates NANs
|===

=== Exponential Functions

- https://en.cppreference.com/w/cpp/numeric/math/exp[exp]
- https://en.cppreference.com/w/cpp/numeric/math/exp2[exp2]
- https://en.cppreference.com/w/cpp/numeric/math/expm1[expm1]
- https://en.cppreference.com/w/cpp/numeric/math/log[log]
- https://en.cppreference.com/w/cpp/numeric/math/log10[log10]
- https://en.cppreference.com/w/cpp/numeric/math/log2[log2]
- https://en.cppreference.com/w/cpp/numeric/math/log1p[log1p]

=== Power Functions

- https://en.cppreference.com/w/cpp/numeric/math/pow[pow]
- https://en.cppreference.com/w/cpp/numeric/math/sqrt[sqrt]
- https://en.cppreference.com/w/cpp/numeric/math/cbrt[cbrt]
- https://en.cppreference.com/w/cpp/numeric/math/hypot[hypot] - Both 2 and 3 arg are supported

=== Trigonometric Functions

- https://en.cppreference.com/w/cpp/numeric/math/sin[sin]
- https://en.cppreference.com/w/cpp/numeric/math/cos[cos]
- https://en.cppreference.com/w/cpp/numeric/math/tan[tan]
- https://en.cppreference.com/w/cpp/numeric/math/asin[asin]
- https://en.cppreference.com/w/cpp/numeric/math/acos[acos]
- https://en.cppreference.com/w/cpp/numeric/math/atan[atan]
- https://en.cppreference.com/w/cpp/numeric/math/atan2[atan2]

=== Hyperbolic Functions

- https://en.cppreference.com/w/cpp/numeric/math/sinh[sinh]
- https://en.cppreference.com/w/cpp/numeric/math/cosh[cosh]
- https://en.cppreference.com/w/cpp/numeric/math/tanh[tanh]
- https://en.cppreference.com/w/cpp/numeric/math/asinh[asinh]
- https://en.cppreference.com/w/cpp/numeric/math/acosh[acosh]
- https://en.cppreference.com/w/cpp/numeric/math/atanh[atanh]

=== Error and Gamma Functions

- https://en.cppreference.com/w/cpp/numeric/math/erf[erf]
- https://en.cppreference.com/w/cpp/numeric/math/erfc[erfc]
- https://en.cppreference.com/w/cpp/numeric/math/tgamma[tgamma]
- https://en.cppreference.com/w/cpp/numeric/math/lgamma[lgamma]

=== Nearest integer floating point operations

- https://en.cppreference.com/w/cpp/numeric/math/ceil[ceil]
- https://en.cppreference.com/w/cpp/numeric/math/floor[floor]
- https://en.cppreference.com/w/cpp/numeric/math/trunc[trunc]
- https://en.cppreference.com/w/cpp/numeric/math/round[round]
- https://en.cppreference.com/w/cpp/numeric/math/round[lround]
- https://en.cppreference.com/w/cpp/numeric/math/round[llround]
- https://en.cppreference.com/w/cpp/numeric/math/nearbyint[nearbyint]
- https://en.cppreference.com/w/cpp/numeric/math/rint[rint]
- https://en.cppreference.com/w/cpp/numeric/math/lrint[lrint]
- https://en.cppreference.com/w/cpp/numeric/math/llrint[llrint]

=== Floating point manipulation functions

- https://en.cppreference.com/w/cpp/numeric/math/frexp[frexp]
- https://en.cppreference.com/w/cpp/numeric/math/ldexp[ldexp]
- https://en.cppreference.com/w/cpp/numeric/math/modf[modf]
- https://en.cppreference.com/w/cpp/numeric/math/scalbn[scalbn]
- https://en.cppreference.com/w/cpp/numeric/math/scalbn[scalbln]
- https://en.cppreference.com/w/cpp/numeric/math/ilogb[ilogb]
- https://en.cppreference.com/w/cpp/numeric/math/logb[logb]
- https://en.cppreference.com/w/cpp/numeric/math/nextafter[nextafter]
- https://en.cppreference.com/w/cpp/numeric/math/nextafter[nexttowards]
- https://en.cppreference.com/w/cpp/numeric/math/copysign[copysign]

=== Classification and comparison

- https://en.cppreference.com/w/cpp/numeric/math/fpclassify[fpclassify]
- https://en.cppreference.com/w/cpp/numeric/math/isfinite[isfinite]
- https://en.cppreference.com/w/cpp/numeric/math/isinf[isinf]
- https://en.cppreference.com/w/cpp/numeric/math/isnan[isnan]
- https://en.cppreference.com/w/cpp/numeric/math/isnormal[isnormal]
- https://en.cppreference.com/w/cpp/numeric/math/signbit[signbit]
- https://en.cppreference.com/w/cpp/numeric/math/isgreater[isgreater]
- https://en.cppreference.com/w/cpp/numeric/math/isgreaterequal[isgreaterequal]
- https://en.cppreference.com/w/cpp/numeric/math/isless[isless]
- https://en.cppreference.com/w/cpp/numeric/math/islesequal[islessequal]
- https://en.cppreference.com/w/cpp/numeric/math/islessgreater[islessgreater]
- https://en.cppreference.com/w/cpp/numeric/math/isunordered[isunordered]

=== Summary

[source, c++]
----

namespace boost {
namespace decimal {

template <typename DecimalType>
constexpr DecimalType abs(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType fabs(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType abs(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType fmod(DecimalType x, DecimalType y) noexcept;

template <typename DecimalType>
constexpr DecimalType remainder(DecimalType x, DecimalType y) noexcept;

template <typename DecimalType>
constexpr DecimalType remquo(DecimalType x, DecimalType y, int* quo) noexcept;

template <typename DecimalType>
constexpr DecimalType fma(DecimalType x, DecimalType y, DecimalType z) noexcept;

template <typename DecimalType>
constexpr DecimalType fmax(DecimalType x, DecimalType y, int* quo) noexcept;

template <typename DecimalType>
constexpr DecimalType fmin(DecimalType x, DecimalType y, int* quo) noexcept;

template <typename DecimalType>
constexpr DecimalType fdim(DecimalType x, DecimalType y, int* quo) noexcept;

constexpr decimal32 nand32(const char* arg) noexcept;
constexpr decimal64 nand64(const char* arg) noexcept;
constexpr decimal128 nand128(const char* arg) noexcept;

template <typename DecimalType>
constexpr DecimalType exp(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType exp2(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType expm1(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType log(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType log10(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType log2(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType log1p(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType pow(DecimalType x, DecimalType y) noexcept;

template <typename DecimalType>
constexpr DecimalType sqrt(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType cbrt(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType hypot(DecimalType x, DecimalType y) noexcept;

template <typename DecimalType>
constexpr DecimalType hypot(DecimalType x, DecimalType y, DecimalType z) noexcept;

template <typename DecimalType>
constexpr DecimalType sin(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType cos(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType tan(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType asin(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType acos(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType atan(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType atan2(DecimalType x, DecimalType y) noexcept;

template <typename DecimalType>
constexpr DecimalType sinh(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType cosh(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType tanh(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType asinh(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType acosh(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType atanh(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType erf(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType erfc(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType tgamma(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType lgamma(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType ceil(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType floor(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType trunc(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType round(DecimalType x) noexcept;

template <typename DecimalType>
constexpr long lround(DecimalType x) noexcept;

template <typename DecimalType>
constexpr long long llround(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType nearbyint(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType rint(DecimalType x) noexcept;

template <typename DecimalType>
constexpr long lrint(DecimalType x) noexcept;

template <typename DecimalType>
constexpr long long llrint(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType frexp(DecimalType x, int* exp) noexcept;

template <typename DecimalType>
constexpr DecimalType ldexp(DecimalType x, int exp) noexcept;

template <typename DecimalType>
constexpr DecimalType modf(DecimalType x, DecimalType* iptr) noexcept;

template <typename DecimalType>
constexpr DecimalType scalbn(DecimalType x, int exp) noexcept;

template <typename DecimalType>
constexpr DecimalType scalbln(DecimalType x, long exp) noexcept;

template <typename DecimalType>
constexpr int ilogb(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType logb(DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType nextafter(DecimalType from, DecimalType to) noexcept;

template <typename DecimalType>
constexpr DecimalType nexttoward(DecimalType from, long double to) noexcept;

template <typename DecimalType>
constexpr DecimalType copysign(DecimalType mag, DecimalType sgn) noexcept;

template <typename DecimalType>
constexpr int fpclassify(DecimalType x) noexcept;

template <typename DecimalType>
constexpr bool isfinite(DecimalType x) noexcept;

template <typename DecimalType>
constexpr bool isinf(DecimalType x) noexcept;

template <typename DecimalType>
constexpr bool isnan(DecimalType x) noexcept;

template <typename DecimalType>
constexpr bool isnormal(DecimalType x) noexcept;

template <typename DecimalType>
constexpr bool signbit(DecimalType x) noexcept;

template <typename DecimalType>
constexpr bool isgreater(DecimalType x, DecimalType y) noexcept;

template <typename DecimalType>
constexpr bool isgreaterequal(DecimalType x, DecimalType y) noexcept;

template <typename DecimalType>
constexpr bool isless(DecimalType x, DecimalType y) noexcept;

template <typename DecimalType>
constexpr bool islessgreater(DecimalType x, DecimalType y) noexcept;

template <typename DecimalType>
constexpr bool isunordered(DecimalType x, DecimalType y) noexcept;

} //namespace decimal
} //namespace boost
----

== C++17 Mathematical Special Functions

The following functions have been implemented for decimal types:

- https://en.cppreference.com/w/cpp/numeric/special_functions/assoc_laguerre[assoc_laguerre]
- https://en.cppreference.com/w/cpp/numeric/special_functions/hermite[hermite]
- https://en.cppreference.com/w/cpp/numeric/special_functions/laguerre[laguerre]

=== Summary

[source, c++]
----

namespace boost {
namespace decimal {

template <typename DecimalType>
constexpr DecimalType assoc_laguerre(unsigned int n, unsigned int m, DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType hermite(unsigned int n, DecimalType x) noexcept;

template <typename DecimalType>
constexpr DecimalType laguerre(unsigned int n, DecimalType x) noexcept;

} //namespace decimal
} //namespace boost
----

== Non-standard Functions

The following are convenience functions, or are prescribed in IEEE 754-2019 as required for decimal floating point types.

=== issignaling

[source, c++]
----
template <typename Decimal>
constexpr bool issignaling(Decimal x) noexcept;
----

Effects: If x is an sNaN returns true, otherwise returns false.

=== samequantum

[source, c++]
----

template <typename Decimal>
constexpr bool samequantum(Decimal x, Decimal y) noexcept;

constexpr bool samequantumd32(decimal32 x, decimal32 y) noexcept;
constexpr bool samequantumd64(decimal64 x, decimal64 y) noexcept;
constexpr bool samequantumd128(decimal128 x, decimal128 y) noexcept;
----

Effects: Determines if the quantum (unbiased) exponents of x and y are the same.

If both x and y are NaN, or infinity, they have the same quantum exponents.

If exactly one operand is infinity or exactly one operand is NaN, they do not have the same quantum exponents.

=== quantexp

[source, c++]
----

template <typename Decimal>
constexpr int quantexp(Decimal x) noexcept;

constexpr int quantexp32(decimal32 x) noexcept;
constexpr int quantexp64(decimal64 x) noexcept;
constexpr int quantexp128(decimal128 x) noexcept;
----

Effects: if x is finite, returns its quantum exponent.

Otherwise, `INT_MIN` is returned.

=== quantized

[source, c++]
----

template <typename Decimal>
constexpr Decimal quantized(Decimal x, Decimal y) noexcept;

constexpr decimal32 quantized32(decimal32 x, decimal32 y) noexcept;
constexpr decimal64 quantized64(decimal64 x, decimal64 y) noexcept;
constexpr decimal128 quantized128(decimal128 x, decimal128 y) noexcept;
----

Returns: a number that is equal in value (except for any rounding) and sign to x, and which has an exponent set to be equal to the exponent of y.

If the exponent is being increased, the value is correctly rounded according to the current rounding mode;

If the result does not have the same value as x, the "inexact" floating-point exception is raised.

If the exponent is being decreased and the significand of the result has more digits than the type would allow, the "invalid" floating-point exception is raised and the result is sNaN.

If one or both operands are NaN the result is sNaN.

Otherwise, if only one operand is infinity, the "invalid" floating-point exception is raised and the result is sNaN.

If both operands are infinity, the result is infinity, with the same sign as x.

The quantize functions do not signal underflow.

=== frexp10

[source, c++]
----
template <typename Decimal>
constexpr auto frexp10(Decimal num, int* expptr) noexcept;

constexpr std::uint32_t frexpd32(decimal32 num, int* expptr) noexcept;
constexpr std::uint64_t frexpd64(decimal64 num, int* expptr) noexcept;
constexpr boost::decimal::detail::uint128 frexpd128(decimal128 num, int* expptr) noexcept;
----

This function is very similar to https://en.cppreference.com/w/cpp/numeric/math/frexp[frexp], but returns the significand and an integral power of 10 since the `FLT_RADIX` of this type is 10.
The significand is normalized to the number of digits of precision the type has (e.g. for decimal32 it is [1'000'000, 9'999'999]).

=== rescale

[source, c++]
----
template <typename Decimal>
constexpr Decimal rescale(Decimal val, int precision = 0);
----

The function returns the decimal type with number of fractional digits equal to the value of precision.
`rescale` is similar to https://en.cppreference.com/w/cpp/numeric/math/trunc[trunc], and with the default precision argument of 0 it is identical.
